[package]
name = "rust-egobox-gp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
egobox-gp = "0.29.0"
ndarray = "0.15"
rand = "0.8"
linfa = "0.7.1"

